### ISSUE TITLE
Create a branch for backmatter section committee edits?

### ISSUE THREAD

**Issue by davidozog** [BryantLam/openshmem-specification#3]
@BryantLam Do you want to create a separate branch to absorb the backmatter section committee edits?  I'm working on issue https://github.com/openshmem-org/specification/issues/296 and am not sure where to post the pull request.

**Comment by BryantLam** [comment]
@davidozog - Done. I created a `sec/backmatter` branch on my fork. It won't be up to date yet, so there will be a lot of diff changes until I fast-forward sync with upstream later. It shouldn't be a problem though.
